[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "node"
command_arguments = [
  "./node_modules/tailwindcss/lib/cli.js",
  "build",
  "-i",
  "src/tailwind.css",
  "-o",
  "dist/.stage/tailwind.css",
]
